version: "3.3"

services:

  site:
    image: docsy/docsy-example
    build:
      context: .
    command: server -b=https://docs.score.dev/docs/ --appendPort=false
    ports:
      - "1313:1313"
    volumes:
      - .:/src
