name: Documentation
description: Report an issue related to documentation
title: "Documentation: "
labels: ["documentation", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make our documentation better!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should be changed in the docs?
      placeholder: A clear and concise description of how the documentation should be updated.
    validations:
      required: true
  - type: checkboxes
    id: check
    attributes:
      label: Is there an existing issue for this?
      description: Please search [our issues](https://github.com/score/score-docs/issues) to see if this bug already exists.
      options:
        - label: I have searched the existing issues.
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/score/score-docs/issues).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    attributes:
      label: Your code.
      description: Copy and paste the code from the editor that you used in between the back-ticks.
      value: |
      ```

      ```
    validations:
      required: false
